language: cpp
compiler:
  - gcc
  - clang

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install cmake qtbase5-dev qtdeclarative5-dev libqt5script5-dev libqt5webkit5-dev libsqlite3-dev

script: mkdir build && cd build && cmake -DUSE_QT5=1 ../ && make
